version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
  nest-api:
    build: .
    image: nest-api-crud:latest
    container_name: nest-api-crud
    ports:
      - 3001:3000
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:3001
    networks:
      - backend
networks:
  backend:
    driver: bridge
