version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roro123
      POSTGRES_DB: nest
    networks:
      - backend
  nest-api:
    build: .
    image: nest-api:v1
    container_name: nest-api-crud
    ports:
      - 3001:3000
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis1
    ports:
      - 6380:3001
    networks:
      - backend
networks:
  backend:
    driver: bridge
